apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: firefly-iii

resources:
  - namespace.yaml
  - postgress_pvc.yaml
  - postgress_deployment.yaml
  - postgress_service.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

configMapGenerator:
  - name: firefly-config
    literals:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=firefly
      - DB_USERNAME=firefly
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - APP_ENV=production
      - TRUSTED_PROXIES=**
      - LOG_CHANNEL=stack

commonLabels:
  app.kubernetes.io/name: firefly-iii
  app.kubernetes.io/part-of: homelab