apiVersion: v1
kind: Service
metadata:
  name: firefly-iii
  namespace: firefly-iii
spec:
  selector:
    app: firefly-iii
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  type: ClusterIP