apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - ../base

secretGenerator:
  - name: grafana-secrets
    literals:
      - admin-password=grafana

patches: 
  - target:
      kind: Deployment
      name: grafana
    path: config-patch.yaml