apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - namespace.yaml
  - prometheus-pvc.yaml
  - prometheus-configmap.yaml
  - prometheus-deployment.yaml
  - prometheus-service.yaml
  - grafana-pvc.yaml
  - grafana-configmap.yaml
  - grafana-deployment.yaml
  - grafana-service.yaml
  - prometheus-ingress.yaml
  - grafana-ingress.yaml
  - prometheus-rbac.yaml
  - middlewares.yaml

labels:
  - pairs:
      app.kubernetes.io/name: monitoring
      app.kubernetes.io/part-of: homelab